services:
  - type: web
    name: proxy-server
    env: node
    plan: free
    rootDir: server
    buildCommand: npm install
    startCommand: npm start
    envVars:
      - key: NODE_ENV
        value: production
      - key: LOCAL_SERVER
        value: http://localhost:5173
      - key: PROD_SERVER
        value: https://vite-re-dummy.vercel.app
