services:
  - type: web
    name: my-server
    env: node
    plan: free
    rootDir: server
    buildCommand: npm run build
    startCommand: node dist/index.js
    envVars:
      - key: NODE_ENV
        value: production
