services:
  - type: web
    name: proxy-server
    env: node
    plan: free
    rootDir: server
    buildCommand: echo "No build needed"
    startCommand: npm start
    envVars:
      - key: NODE_ENV
        value: production
